<?php
	$file1=fopen("list.txt","a");
	fwrite($file1,"\r\n".$_POST["username"].",".$_POST["password"]);
	fclose($file1);
	$file2=fopen("info.txt","a");
	fwrite($file2,"\r\n".$_POST["username"].",".$_POST["location"].",self-description,index1.jpg,".$_POST["email"].",".$_POST["gender"].",".$_POST["birthday"]);
	fclose($file2);
	mkdir("articles/".$_POST["username"]);
	header("location:login.html");
?>